### ISSUE TITLE
Had to play my card several times

### ISSUE THREAD

**Issue by spectralsun** [dean/cah_bot#30]
I used the play command, but it was apparently not registering. I was told in my status buffer to play a card, after I used the play command.

I ended up doing play 3 times.

The game also supposedly played a card that @rettigs didn't actually tell it to play.

**Comment by rettigs** [comment]
Same thing happened to me yesterday.

**Comment by dean** [comment]
Just as an FYI, your card was played, the thing that was broken was the reminder to play.

**Comment by rettigs** [comment]
There was also at least one instance where `!gamestatus` showed that everyone had played (except the dealer), but it didn't send the cards to the judge.  It kept sending the "please choose a winner".  I was able to pick a winner blindly however by doing `!winner 1`.

**Comment by dean** [comment]
For a lot of these, I have no way to reproduce without instructions or screenshots. If you have those, it would help a ton. :)
